### ISSUE TITLE
Enabling "Show history rates" will result Electrum-Firo crash.

### ISSUE THREAD

**Issue by DNS** [firoorg/electrum-firo#16] opened 2022-06-21 15:04 UTC
## Actual behavior
Enabling `Show history rates` will result in Electrum-Firo crash.
After the crash, clicking `Preferences` will result in crash.

## Steps to reproduce
1. Click menu `Tools > Preferences > Fiat`
2. Select `Fiat currency to USD`
3. `Show history rates` (Ticked/Enabled)
4. It will result in Crash.
5. After the crash, running Electrum-Firo and then clicking `Preferences` again will result in crash.

In order to reset Electrum-Firo, I must delete all files in this directory:
`C:\Users\%USERNAME%\AppData\Roaming\Electrum-FIRO`
And then run Electrum-Firo again.

## OS, Version
1. Windows 10 1809, 64-bit
2. [Firo-Electrum-4.1.5.1-setup-win64.exe](https://github.com/firoorg/electrum-firo/releases/download/4.1.5.1/Firo-Electrum-4.1.5.1-setup-win64.exe)

![image](https://user-images.githubusercontent.com/37093/174832658-bf4b616d-218f-438f-bc46-f79456a9ff48.png)

**Comment by justanwar** [comment] 2022-06-23 06:19
Duplicate of #15, but please try the step in this comment: https://github.com/firoorg/electrum-firo/issues/15#issuecomment-1135547695

**Comment by justanwar** [comment] 2023-02-26 09:54
Fixed in #39

**Closed by justanwar** 2023-02-26 09:54 UTC
