### ISSUE TITLE
Unable to connect FIRO wallet to Ledger

### ISSUE THREAD

**Issue by Rameshmohata** [firoorg/electrum-firo#14] opened 2022-05-03 09:57 UTC
Hardware Keystore
No hardware device detected.
To trigger a rescan, press 'Next'.

If your device is not detected on Windows, go to "Settings", "Devices", "Connected devices", and do "Remove device". Then, plug your device again.
While this is less than ideal, it might help if you run Electrum as Administrator.

Debug message
  ledger: (error getting device infos)
    read error

**Comment by justanwar** [comment] 2022-05-15 16:23
Duplicate of #13

**Closed by justanwar** 2022-05-15 16:23 UTC
