### ISSUE TITLE
Can't connect Ledger devices: "Device not in Dash mode"

### ISSUE THREAD

**Issue by staguigue-ledger** [firoorg/electrum-firo#52] opened 2024-05-24 13:13 UTC
### Actual behavior
When trying to connect a Ledger Nano X or Nano S Plus to Electrum Firo, the error "Device not in Dash mode" is shown. 

### Steps to reproduce
1. Open the FIRO app on your Ledger Nano X or Nano S Plus
2. Try to establish a connection with Firo Wallet

### Crash / debug logs
![image](https://github.com/firoorg/electrum-firo/assets/89529968/be746647-74af-4b21-b007-3b4d388c3ec7)

**Comment by justanwar** [comment] 2024-05-24 13:49
What is the Firo app version?

**Comment by staguigue-ledger** [comment] 2024-05-27 09:48
Hi @justanwar 
Firo app version is 2.4.1

**Comment by justanwar** [comment] 2024-05-27 09:56
@staguigue-ledger Users report that previous version of Firo app (2.2.0) worked on Electrum Firo 4.1.5.3 for Nano/X/S/S Plus, but Firo app 2.4.1 does not. We have not changed anything on our end.

Are you from Ledger?

**Comment by vforgeoux-ledger** [comment] 2024-06-06 15:13
Hey @justanwar , you're right it seems that Electrum forks are facing issues with device detection after the 2.4.1 app update for Bitcoin clones. We're trying to find the root cause of the issue but if you have any idea feel free to share it here. 
If it helps, the same issue has been reported for Litecoin 2.4.1 app version (which shares the same codebase as Firo app (https://github.com/LedgerHQ/app-bitcoin). Electrum-LTC throws the same error message, while we didn't notice any regression on Ledger Live.

**Comment by 77explode** [comment] 2024-06-21 19:00
So what are the news?
Is it possible to downgrade app at ledger?

@vforgeoux-ledger @staguigue-ledger @meriadec @noirbizarre @valpinkman @pollastri-pierre @MrFreezeex @mbertin-ledger @laitali-ledger @KVNLS @jcchevalier-ledger @hedi-edelbloute @dgreen-ledger @CremaFR @Canestin @b0l0k @AEnguerrand @aelmilligy-ledger @abonnaudet-ledger

**Comment by justanwar** [comment] 2024-07-03 17:48
Fixed with Firo app 2.4.5 and #57.

**Closed by justanwar** 2024-07-03 17:48 UTC
